clothshop/clothshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothshop/main/urls.py
from django.urls import path,include
from . import views



urlpatterns=[
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('search',views.search,name='search'),
    path('category-list',views.category_list,name='category-list'),
    path('brand-list',views.brand_list,name='brand-list'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('brand-product-list/<int:brand_id>',views.brand_product_list,name='brand-product-list'),
    path('product/<str:slug>/<int:id>',views.product_detail,name='product_detail'),
    path('filter-data',views.filter_data,name='filter_data'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('add-to-cart',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart_list,name='cart'),
    path('delete-from-cart',views.delete_cart_item,name='delete-from-cart'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('accounts/signup',views.signup,name='signup'),
    path('checkout/',views.checkout,name='checkout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('save-review/<int:pid>',views.save_review, name='save-review'),
    # User Section Start
    path('my-dashboard',views.my_dashboard, name='my_dashboard'),
    path('my-orders',views.my_orders, name='my_orders'),
    path('my-orders-items/<int:id>',views.my_order_items, name='my_order_items'),
    # End

    # Wishlist
    path('add-wishlist',views.add_wishlist, name='add_wishlist'),
    path('my-wishlist',views.my_wishlist, name='my_wishlist'),
    # My Reviews
    path('my-reviews',views.my_reviews, name='my-reviews'),
    # My AddressBook
    path('my-addressbook',views.my_addressbook, name='my-addressbook'),
    path('add-address',views.save_address, name='add-address'),
    path('activate-address',views.activate_address, name='activate-address'),
    path('update-address/<int:id>',views.update_address, name='update-address'),
    path('edit-profile',views.edit_profile, name='edit-profile'),
]

clothshop/main/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User


# Banner
class Banner(models.Model):
    img = models.ImageField(upload_to="banner_imgs/")
    alt_text = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.img.url))

    def __str__(self):
        return self.alt_text


# Category
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural = '2. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


# Brand
class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="brand_imgs/")

    class Meta:
        verbose_name_plural = '3. Brands'

    def __str__(self):
        return self.title


# Color
class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title


# Size
class Size(models.Model):
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '5. Sizes'

    def __str__(self):
        return self.title


# Product Model
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = '6. Products'

    def __str__(self):
        return self.title


# Product Attribute
class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="product_imgs/", null=True)

    class Meta:
        verbose_name_plural = '7. ProductAttributes'

    def __str__(self):
        return self.product.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))


# Order
status_choice = (
    ('process', 'In Process'),
    ('shipped', 'Shipped'),
    ('delivered', 'Delivered'),
)


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amt = models.FloatField()
    paid_status = models.BooleanField(default=False)
    order_dt = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(choices=status_choice, default='process', max_length=150)

    class Meta:
        verbose_name_plural = '8. Orders'


# OrderItems
class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=150)
    item = models.CharField(max_length=150)
    image = models.CharField(max_length=200)
    qty = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()

    class Meta:
        verbose_name_plural = '9. Order Items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))


# Product Review
RATING = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_text = models.TextField()
    review_rating = models.CharField(choices=RATING, max_length=150)

    class Meta:
        verbose_name_plural = 'Reviews'

    def get_review_rating(self):
        return self.review_rating


# WishList
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Wishlist'


# AddressBook
class UserAddressBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=50, null=True)
    address = models.TextField()
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'AddressBook'


class Contact(models.Model):
    name=models.CharField(max_length=25)
    email=models.EmailField()
    phoneNumber=models.CharField(max_length=12)
    description=models.TextField(max_length=250)

    def __str__(self) :
        return self.name

clothshop/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1>Welcome to About Page</h1>
  </div>  
{% endblock  %}

clothshop/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if data %}
			{% for brand in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				<a href="/brand-product-list/{{brand.id}}"><img src="/media/{{brand.image}}" class="card-img-top" alt="{{brand.title}}" /></a>
				<div class="card-body">
					<h6 class="card-text"><a href="#">{{brand.title}}</a></h6>
				</div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

clothshop/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
						  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
						  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
						  	<span class="float-right">
						  		4.5/5
						  		<i class="fa fa-star text-warning"></i>
						  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

clothshop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Cart ({{totalitems}})</h3>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Product</th>
				<th>Qty</th>
				<th>Price</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			{% for product_id,item in cart_data.items %}
			<tr>
				<td>
					<img src="/media/{{item.image}}" width="50" />
					<p><a href="/product/{{item.title|slugify}}/{{product_id}}">{{item.title}}</a></p>
				</td>
				<td>
					<input type="number" class="product-qty-{{product_id}}" value="{{item.qty}}" style="vertical-align: bottom;" />
					<button class="btn btn-sm btn-primary update-item" data-item="{{product_id}}"><i class="fa fa-sync"></i></button>
					<button class="btn btn-sm btn-danger delete-item" data-item="{{product_id}}"><i class="fa fa-trash"></i></button>
				</td>
				<td>$ {{item.price}}</td>
				<td>$ {% widthratio item.price 1 item.qty %}</td>
			</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<td colspan="2"></td>
				<th>Total</th>
				<th>Rs. {{total_amt}}</th>
			</tr>
			{% if totalitems %}
			<tr>
				<td colspan="4" align="right">
					<a href="{% url 'checkout' %}" class="btn btn-dark btn-sm">Checkout <i class="fa fa-long-arrow-alt-right"></i></a>
				</td>
			</tr>
			{% endif %}
		</tfoot>
	</table>
</main>
{% endblock %}

clothshop/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
		{% if data %}
			{% for cat in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				<a href="/category-product-list/{{cat.id}}"><img src="/media/{{cat.image}}" class="card-img-top" alt="{{cat.title}}" /></a>
				<div class="card-body">
					<h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
				</div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

clothshop/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

clothshop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
	<!-- Featured Products -->
	<div class="row">
		<div class="col-md-9">
			<h3 class="my-4 border-bottom pb-1">Cart ({{totalitems}})</h3>
			<table class="table table-bordered">
		<thead>
			<tr>
				<th>Product</th>
				<th>Qty</th>
				<th>Price</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			{% for product_id,item in cart_data.items %}
			<tr>
				<td>
					<img src="/media/{{item.image}}" width="50" />
					<p><a href="/product/{{item.title|slugify}}/{{product_id}}">{{item.title}}</a></p>
				</td>
				<td>
					{{item.qty}}
				</td>
				<td>$ {{item.price}}</td>
				<td>$ {% widthratio item.price 1 item.qty %}</td>
			</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<td colspan="2"></td>
				<th>Total</th>
				<th>Rs. {{total_amt}}</th>
			</tr>
			{% if totalitems %}
			<tr>
				<td colspan="4" align="right">
					{{form.render}}
				</td>
			</tr>
			{% endif %}
		</tfoot>
	</table>
		</div>
		<div class="col-md-3">
			<h3 class="my-4 border-bottom pb-1">Selected Address</h3>
			<div class="card">
				<div class="card-body">
					<p>{{address.address}}</p>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

clothshop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
      {% endif %}
      <img src="/media/{{banner.img}}" class="d-block w-100" alt="...">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
          <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
			  </div>
			  <div class="card-footer">
          {{product.productattribute_set.first.color.title}}
          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
          {% if user.is_authenticated %}
			  	<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
          {% else %}
          <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
          {% endif %}
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
    {% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

clothshop/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">{{data.title}}</h3>
	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" data-zoom-image="/media/{{data.productattribute_set.first.image}}" src="/media/{{data.productattribute_set.first.image}}" class="card-img-top" alt="{{data.title}}">
		</div>
		<div class="col-md-8">
			<p>{{data.detail}}</p>
			<hr/>
			<table class="table table-bordered">
				<tr>
					<th>Colors</th>
					<td>
						{% for color in colors %}
							<button class="btn btn-lg choose-color" data-color="{{color.color__id}}" style="background-color: {{color.color__color_code}}"></button>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<th>Sizes</th>
					<td>
						{% for size in sizes %}
						<button data-price="{{size.price}}" class="btn btn-outline-secondary btn-sm choose-size color{{size.color__id}}">{{size.size__title}}</button>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<th>Price</th>
					<th>$ <span class="product-price-{{data.id}}">{{data.productattribute_set.first.price}}</span></th>
				</tr>
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" value="1" class="form-control product-qty-{{data.id}}" id="productQty" />
			  <div class="input-group-append">
			  	<input type="hidden" class="product-image-{{data.id}}" value="{{data.productattribute_set.first.image}}" />
		          <input type="hidden" class="product-id-{{data.id}}" value="{{data.id}}" />
		          <input type="hidden" class="product-title-{{data.id}}" value="{{data.title}}" />
			    <button class="btn btn-primary btn-sm add-to-cart" data-index="{{data.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
			  </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-md-6">
			<h3 class="my-3">Detail</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Brand</th>
					<td><a href="/brand-product-list/{{data.brand.id}}">{{data.brand.title}}</a></td>
				</tr>
				<tr>
					<th>Category</th>
					<td><a href="/category-product-list/{{data.category.id}}">{{data.category.title}}</a></td>
				</tr>
				<tr>
					<th>Specification</th>
					<td>{{data.specs}}</td>
				</tr>
			</table>
		</div>
		<!-- Reviews -->
		<div class="col-md-6">
			<h3 class="my-3">Reviews - <span class="avg-rating">{{avg_reviews.avg_rating}}</span>/5 <i class="fa fa-star text-warning"></i>
				{% if user.is_authenticated %}
				{% if canAdd %}
				<button data-toggle="modal" data-target="#productReview" type="button" class="btn btn-warning btn-sm float-right reviewBtn">Add Review</button>
				{% endif %}
				{% endif %}
			</h3>
	{% if user.is_authenticated %}
	<!-- Product Review -->
	<div class="modal fade" id="productReview" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Add Product Review</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	<form method="post" id="addForm" action="{% url 'save-review' data.id %}">
	      		{% csrf_token %}
		      	<table class="table table-bordered">
		      		{{reviewForm.as_table}}
		      		<tr>
		      			<td colspan="2">
		      				<button type="submit" class="btn btn-primary">Submit</button>
		      				<input type="reset" class="btn btn-dark" value="Reset" id="reset" />
		      			</td>
		      		</tr>
		      	</table>
		      	<p class="ajaxRes"></p>
	      </form>
	      </div>
	    </div>
	  </div>
	</div>
	<!-- Product Review End -->
	{% endif %}
			</h3>
			<div class="card">
				<div class="card-body review-list" style="max-height: 400px; overflow: auto;">
					<!-- Detail -->
					{% if reviews %}
						{% for review in reviews %}
						<blockquote class="blockquote text-right">
						  <small>{{review.review_text}}</small>
						  <footer class="blockquote-footer">{{review.user}} 
						  	<cite title="Source Title">
						  		{% for star in review.review_rating|ljust:review.review_rating %}
						  		<i class="fa fa-star text-warning"></i>
								{% endfor %}
						  	</cite>
						  </footer>
						</blockquote>
						<hr />
						{% endfor %}
					{% else %}
						<p class="no-data">Add First Review</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<!-- Related Products -->
	<h3 class="mt-4 mb-3 border-bottom pb-1">Related Products</h3>
	<div class="row">
		{% for product in related %}
		<div class="col-lg-3 col-sm-4 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
<!-- Image Zoom -->
<script src="{% static 'jquery.ez-plus.js' %}"></script>
<script type="text/javascript">
    $('#zoom_01').ezPlus();
</script>

<!-- Add To Cart -->
<script src="{% static 'custom.js' %}"></script>

{% endblock %}

clothshop/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}